import os
from PIL import Image, ImageFilter

workspace_dir = r"C:\Users\Jerry\.gemini\antigravity\scratch\moodtracker"
folder = os.path.join(workspace_dir, "public", "學校圖檔", "吉祥物")
body_path = os.path.join(folder, "xinxin_body_base_v8.png")

if not os.path.exists(body_path):
    print("xinxin_body_base_v8.png not found!")
    exit(1)

with Image.open(body_path) as img:
    img = img.convert("RGBA")
    
    # We want to blur the pedestal transition lines.
    # The neck pedestal is generated by copying row 704 vertically for y in [650, 703], x in [212, 524].
    # This creates harsh vertical stripes.
    # We crop the pedestal region. Let's include a tiny bit of the shoulders below y=704 (e.g. up to y=715) to make it smooth.
    crop_box = (212, 650, 525, 715)
    neck_crop = img.crop(crop_box)
    
    # Let's apply a Gaussian blur to soften the vertical columns
    blurred_neck = neck_crop.filter(ImageFilter.GaussianBlur(radius=8))
    
    # Paste back
    img.paste(blurred_neck, crop_box)
    
    img.save(body_path, "PNG")
    print("Successfully blurred the neck pedestal on xinxin_body_base_v8.png!")
